### ISSUE TITLE
Notifications 

### ISSUE THREAD

**Issue by d51x** [u236/homed-frontend-zigbee#1]
Добавить всплывающие уведомления на события:
1. Устройство покинуло сеть
2. Джойн/реджойн устройства
3. Устройство прошло интервью / ошибка интервью

При успешной операции уведомления зелёные / голубые 
При не успешной - красные / розовые

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-frontend-zigbee/commit/b442cbba48dacfcd8c20809ecd68b4bc80f10ec3  и https://github.com/u236/homed-service-zigbee/commit/67b2492f7c1fdbd1e275c6cd803251904dba612f
